language: java
dist: trusty
jdk: openjdk8
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - mvn clean package -Dmaven.test.skip=true
addons:
  sonarcloud:
    organization: "ptitguigui"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=ptitguigui

